### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by djmoffat** [drscotthawley/signaltrain#24]
It seems as though the DNS for the associated website is down, or the website has expired.

**Comment by drscotthawley** [comment]
Woops!  Thanks for letting me know, Dave.  I saw you post this 21 days ago and have been distracted.  I'll work at getting it back -- the problem with free ".ml" domains.  I used that for anonymity when submitting the paper. 

Until then, the direct link to where the demo "really" lives is at https://signaltrain.herokuapp.com.  That still works.

**Comment by drscotthawley** [comment]
Got the original URL re-registered.  DNS updates should get pushed sometime within the next 48 hours.

**Comment by drscotthawley** [comment]
...and it's back up at http://www.signaltrain.ml  In this case it's just forwarding to heroku.  
Closing.
