### ISSUE TITLE
Link in README redirects to spam site

### ISSUE THREAD

**Issue by akalmbach-kinsol** [drscotthawley/signaltrain#26]
http://www.signaltrain.ml/ linked as the demo page in the README file is redirecting to a very sketchy spam website. I suspect you'll want to serve your demo over an HTTPS connection instead.

**Comment by drscotthawley** [comment]
Thanks!  Yea after a couple years I stopped renewing the URL.
Thought I updated the URL to go straight to Heroku, but looks like I missed a spot.  Now fixed in  commit # https://github.com/drscotthawley/signaltrain/commit/7d93cb4b63cc4ebd1a2f7a06e3192d755f56739d.
